export enum EOObject {
  CO_SO_DAO_TAO = 'CO_SO_DAO_TAO',
  NAM_HOC = 'NAM_HOC',
  HOC_KY = 'HOC_KY',
  LOP_TIN_CHI = 'LOP_TIN_CHI',
  KHOA_SINH_VIEN = 'KHOA_SINH_VIEN',
  KHOA = 'KHOA',
  NGANH = 'NGANH',
  LOP_HANH_CHINH = 'LOP_HANH_CHINH',
  CHUYEN_NGANH = 'CHUYEN_NGANH',
  HINH_THUC_DAO_TAO = 'HINH_THUC_DAO_TAO',
}
