export const LoaiDon = {
  'Công tác chính trị sinh viên': [
    // 'Tất cả đơn phòng CTCTSV',
    'Yêu cầu cấp giấy xác nhận tình trạng học tập',
    'Yêu cầu cấp giấy xác nhận hồ sơ ưu đãi giáo dục',
    'Yêu cầu cấp giấy giới thiệu',
    'Yêu cầu cấp giấy xác nhận vay vốn sinh viên',
    'Yêu cầu cấp giấy đăng ký vé tháng xe buýt',
    'Đơn đề nghị miễn, giảm học phí',
  ],
  'Giáo vụ': [
    // 'Tất cả đơn phòng giáo vụ',
    'Đơn đề nghị cấp lại, đổi thẻ sinh viên',
    'Đơn xin học môn học thay thế',
    'Đơn đề nghị',
    'Đơn xin dự thi',
    'Đơn xin ngừng học',
    'Đơn xin thôi học',
    'Đơn đề nghị cấp thẻ sinh viên',
    'Đơn xin trở lại học tập',
    'Đơn xin chuyển trường',
    'Đơn đề nghị cấp bảng điểm cá nhân',
    'Đơn đề nghị cấp chứng nhận hoàn thành khóa học',
    'Đơn đề nghị được công nhận đạt chuẩn đầu ra Tiếng Anh',
    'Đơn đề nghị miễn học - miễn thi (các học phần tiếng anh) (mẫu 1)',
    'Đơn đề nghị miễn học - miễn thi (các học phần tiếng anh) (mẫu 2)',
    'Đơn đề nghị được chuyển đổi điểm (các học phần tiếng anh) (mẫu 1)',
    'Đơn đề nghị được chuyển đổi điểm (các học phần tiếng anh) (mẫu 2)',
    'Đơn xin miễn học - miễn thi - tạm hoãn học phần: giáo dục thể chất, giáo dục quốc phòng',
    'Đơn xin miễn học, miễn thi',
    'Đơn xin học ngành thứ hai',
    'Đơn đăng ký được xét tốt nghiệp',
  ],
  'Trung tâm khảo thí': [
    // 'Tất cả đơn trung tâm khảo thí',
    'Đơn xin vắng thi',
    'Đơn đăng ký dự thi chuẩn đầu ra Tiếng Anh',
    'Đơn đề nghị thi ghép',
    'Đơn đề nghị xem xét điểm thi kết thúc học phần',
  ],
  'Văn phòng số': [
    'Phiếu đăng ký xe đi công tác',
    'Giấy báo thay thế sửa chữa',
    'Phiếu đăng ký lịch công tác tuần của Học viện',
    // 'Tất cả đơn văn phòng số',
  ],
};

export const PhongBan = {
  ctctsv: 'Công tác chính trị sinh viên',
};
